# Baseline VAE configuration for alanine dipeptide φ/ψ inputs (no topology loss).
dataset:
  path: data/alanine_dipeptide/phi_psi.npy
  representation: dihedral
  geometry: dihedral
  train_fraction: 0.7
  val_fraction: 0.15
  test_fraction: 0.15
  seed: 123

model:
  latent_dim: 2
  hidden_dims: [128, 64]
  center_inputs: False
  geometry: dihedral

training:
  epochs: 100
  batch_size: 512
  learning_rate: 0.001
  weight_decay: 0.0
  beta: 0.01
  max_steps: null
  log_every: 50
  checkpoint_every: 500
  output_dir: runs/alanine_dipeptide/baseline
  seed: 42
  device: auto

topology:
  enabled: False

logging:
  backend: tensorboard
  project: topo-ala-dipeptide
